apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-delivery"
spec:
  stages:
    - name: "qa"
      sequences:
        - name: "loadtest-execution"
          tasks:
            - name: "test"
              properties:
                teststrategy: performance
        - name: "loadtest-evaluation"
          tasks:
            - name: "evaluation"
              properties:
                timeframe: 10m
        - name: "loadtest-execution-and-evaluation"
          tasks:
            - name: "test"
            - name: "evaluation"
